In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("data/ANN 재공현황.xlsx")
data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,CRT_DT,CRTCHR_NO,UPD_DT,UPDCHR_NO,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
0,1173DK,07KC1022111A,2007KC1022,07KC1022111,92311302,07KC1022111,NaN,1282N,NaN,NaN,...,2007-03-06 00:00:00,MGTEST,2019-07-12 14:50:02,이승용,NaT,NaN,NaN,NaN,E,1510P
1,1173DK,07KC1022211A,2007KC1022,07KC1022211,92311302,07KC1022211,NaN,1282N,NaN,NaN,...,2007-03-07 00:00:00,MGTEST,2013-01-16 14:26:12,김덕림,NaT,NaN,NaN,NaN,E,1510P
2,1173DK,07KC1022311A,2007KC1022,07KC1022311,92311302,07KC1022311,NaN,1282N,NaN,NaN,...,2007-03-07 00:00:00,MGTEST,2020-03-18 22:52:12,김백수,NaT,NaN,NaN,NaN,E,1510P
3,1173DK,07KK1D22111,2007KK1D22,07KK1D22111,HAT052900,NaN,NaN,NaN,NaN,NaN,...,2011-09-29 09:14:46,강연철,2021-02-09 10:08:53,이승용,NaT,NaN,NaN,1055A,E,1510P
4,1173DK,09KA1B77311,2009KA1B77,09KA1B77311,HAN026620,NaN,NaN,1282N,NaN,NaN,...,2010-01-01 00:00:00,MGTEST,2011-05-30 22:34:02,김도경,NaT,NaN,NaN,NaN,E,1510P

In [3]:
# 수정자
data.drop("UPDCHR_NO", axis = 1, inplace=True)
# 생성자 
data.drop("CRTCHR_NO", axis = 1, inplace=True)

### 규격

In [4]:
PRDSPC_ID_unique = data["PRDSPC_ID"].unique()
PRDSPC_ID_unique

array(['SCP1-H-B', 'S45CM-S', '50CRV4M-S', 'S55CM-R', 'SK5M-S', 'S35CM-R',
       'S55CM-S', 'S20CM-R', 'SCP1-S-B', '50CRV4M-R', 'DK800',
       'SAE1070M-R', 'S45C-PA', 'SAE1552M-R', '16MNCR5M-S', 'SAE1055M-R',
       'CK75M2', 'SK85', 'SK85M-S', 'S20CM-S', 'S15CM-S', 'S70CM-AD',
       'SAE1074M-R', '16MNCR5M2', 'S45CM-R', 'S50CM-S', 'CK75M3',
       'SAE1045M-S', 'C80M', 'SK4M-S', 'SK85M-R', 'SK5M-R', 'SK4M-R',
       'H800LA', 'SAE1020', 'SPCC-1BP', 'SAE1010H', 'SPCC-2B',
       'SCP1-1/2H-B', '51CRV4M-S', 'SAE1050M-R', 'C67S', 'SNCM220M-S',
       'SNCM220-PA', 'S35CM-S', 'C75S-HT', 'SK85M', 'SCM430M-S',
       'SAE1010M-R', 'SAE1070M-S', '100CR6'], dtype=object)

## 특별 CYCLE 규격

In [5]:
special_cycle_code = np.array(["DK800","S700MC","H800LA","S55C-PA","S45CM-R","SAE1050-PA","SAE1050M-A",
                                "SK2M-R(PPC)","SK4M-R(PPC)","SK5M-R(PPC)","SK4M-R","SK5M-R","SKS51M-R",
                                "SKS81M-R","SAE1074M-R","S55CM-S","SCM435M-S","SK5M-S""51CRV4M-S","CK75M2",
                                "CK75M3","C80M","SK강","SK85","100CR6","100CR6-PA","SUJ2","SAE52100","AISI4140M-S","50CRV4M-S","S45CM-R"])

## 일반 CYCLE 규격

In [6]:
general_cycle_code = np.setdiff1d(PRDSPC_ID_unique, special_cycle_code)
general_cycle_code

array(['16MNCR5M-S', '16MNCR5M2', '50CRV4M-R', '51CRV4M-S', 'C67S',
       'C75S-HT', 'S15CM-S', 'S20CM-R', 'S20CM-S', 'S35CM-R', 'S35CM-S',
       'S45C-PA', 'S45CM-S', 'S50CM-S', 'S55CM-R', 'S70CM-AD', 'SAE1010H',
       'SAE1010M-R', 'SAE1020', 'SAE1045M-S', 'SAE1050M-R', 'SAE1055M-R',
       'SAE1070M-R', 'SAE1070M-S', 'SAE1552M-R', 'SCM430M-S',
       'SCP1-1/2H-B', 'SCP1-H-B', 'SCP1-S-B', 'SK4M-S', 'SK5M-S', 'SK85M',
       'SK85M-R', 'SK85M-S', 'SNCM220-PA', 'SNCM220M-S', 'SPCC-1BP',
       'SPCC-2B'], dtype=object)

## DYNAX CORP.

In [7]:
DYNAX_CORP = np.array(["S55C-PA"])

In [8]:
DYNAX_CORP_data = data[data["PRDSPC_ID"] == DYNAX_CORP[0]]
DYNAX_CORP_data.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

##

## 한국보그워너티에스
### ANN1차 620

In [9]:
HKBOG = np.array(["S45CM-R"])

In [10]:
HKBOG_data = data[data["PRDSPC_ID"] == HKBOG[0]]
HKBOG_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
77,1173DK,22G122021111A,2022G12202,22G12202111,CRW397701,22G12202111,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
78,1173DK,22G122021121A,2022G12202,22G12202112,CTX443601,22G12202112,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
79,1173DK,22G122022111A,2022G12202,22G12202211,CRW397701,22G12202111,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
80,1173DK,22G122022121A,2022G12202,22G12202212,CTX443601,22G12202112,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
81,1173DK,22G122023111A,2022G12202,22G12202311,CRW397701,22G12202111,103.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P

### ANN 0차

In [11]:
HKBOG_data_ANN0 = HKBOG_data[HKBOG_data["PNSPRC_CD"] == "AN10"]
HKBOG_data_ANN0.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

In [12]:
HKBOG_data_ANN0_size = len(HKBOG_data_ANN0)
HKBOG_data_ANN0_size

0

### ANN 1차 이상

In [13]:
HKBOG_data_ANN1 = HKBOG_data[HKBOG_data["PNSPRC_CD"] != "AN10"]
HKBOG_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
77,1173DK,22G122021111A,2022G12202,22G12202111,CRW397701,22G12202111,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
78,1173DK,22G122021121A,2022G12202,22G12202112,CTX443601,22G12202112,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
79,1173DK,22G122022111A,2022G12202,22G12202211,CRW397701,22G12202111,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
80,1173DK,22G122022121A,2022G12202,22G12202212,CTX443601,22G12202112,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
81,1173DK,22G122023111A,2022G12202,22G12202311,CRW397701,22G12202111,103.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P

In [14]:
HKBOG_data_ANN1_size = len(HKBOG_data_ANN1)
HKBOG_data_ANN1_size

6

## (주)지에스앤티

In [15]:
GSNT = np.array(["SAE1050-PA","SAE1050M-A"])

In [16]:
GSNT_data = data[(data["PRDSPC_ID"] == GSNT[0]) | (data["PRDSPC_ID"] == GSNT[1])]
GSNT_data.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

## 일진엔티에스(주)

### 일진엔티에스1 : 625 , 625

In [17]:
ILJINNTS_1 = np.array(["SK2M-R(PPC)","SK4M-R(PPC)","SK5M-R(PPC)"])

In [18]:
ILJINNTS_1_data = data[(data["PRDSPC_ID"] == ILJINNTS_1[0]) |(data["PRDSPC_ID"] == ILJINNTS_1[1]) | (data["PRDSPC_ID"] == ILJINNTS_1[2]) ]
len(ILJINNTS_1_data)

0

### 일진엔티에스2 : 750, 700(표준)

In [19]:
ILJINNTS_2 = np.array(["SK4M-R","SK5M-R","SKS51M-R","SKS81M-R"])

In [20]:
ILJINNTS_2_data = data[(data["PRDSPC_ID"] == ILJINNTS_2[0]) |(data["PRDSPC_ID"] == ILJINNTS_2[1]) | (data["PRDSPC_ID"] == ILJINNTS_2[2]) | (data["PRDSPC_ID"] == ILJINNTS_2[3]) ]
len(ILJINNTS_2_data)

4

###  PNSPRC_CD : 현공정코드
- AN10 : ANN 0차
- AN11 : ANN 1차
- AN12 : ANN 2차
- AN13 : ANN 3차

### ANN0차

In [21]:
ILJINNTS_2_data_ANN0 = ILJINNTS_2_data[ILJINNTS_2_data["PNSPRC_CD"] == "AN10"]
ILJINNTS_2_data_ANN0

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
361,1173DK,22H130252111A,2022H13025,22H13025211,HBF072770,22H13025111,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-02 04:54:38,2022-09-05 15:46:06,NaT,NaN,NaN,1055A,L,1510P

In [22]:
ILJINNTS_2_data_ANN0_size = len(ILJINNTS_2_data_ANN0)
ILJINNTS_2_data_ANN0_size

1

### ANN1차이상

In [23]:
ILJINNTS_2_data_ANN1 = ILJINNTS_2_data[ILJINNTS_2_data["PNSPRC_CD"] != "AN10"]
ILJINNTS_2_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
132,1173DK,22G13050111,2022G13050,22G13050111,HBF162820,22G13050111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-25 13:28:39,2022-09-15 02:46:12,NaT,NaN,NaN,1055A,E,1510P
133,1173DK,22G13053111,2022G13053,22G13053111,HBF162720,22G13053111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-27 10:21:28,2022-09-15 01:26:57,NaT,NaN,NaN,1055B,E,1510P
364,1173DK,22H13032111,2022H13032,22H13032111,HBF072850,22H13032111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-17 09:32:07,2022-09-03 08:55:11,NaT,NaN,NaN,1055C,E,1510P

In [24]:
ILJINNTS_2_data_ANN1_size = len(ILJINNTS_2_data_ANN1)
ILJINNTS_2_data_ANN1_size

3

## JMI

In [25]:
JMI = np.array(["SAE1074M-R"])

In [26]:
JMI_data = data[data["PRDSPC_ID"] == JMI[0]]
JMI_data

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
63,1173DK,22G12107111,2022G12107,22G12107111,HBZ078470,22G12107111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-11 17:07:37,2022-09-05 12:55:33,NaT,NaN,NaN,1055A,E,1510P

### ANN 0차

In [27]:
JMI_data_ANN0 = JMI_data[JMI_data["PNSPRC_CD"] == "AN10"]
JMI_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
63,1173DK,22G12107111,2022G12107,22G12107111,HBZ078470,22G12107111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-11 17:07:37,2022-09-05 12:55:33,NaT,NaN,NaN,1055A,E,1510P

In [28]:
JMI_data_ANN0_size = len(JMI_data_ANN0)
JMI_data_ANN0_size

1

### ANN 1차 이상

In [29]:
JMI_data_ANN1 = JMI_data[JMI_data["PNSPRC_CD"] != "AN10"]
JMI_data_ANN1.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

In [30]:
JMI_data_ANN1_size = len(JMI_data_ANN1)
JMI_data_ANN1_size

0

## (주)정민스틸 / (주)대성파인텍 / 지에스앤티 / (주)화진금속

In [31]:
JM_DS_GS_HJ = np.array(["S55CM-S","SCM435M-S","SK5M-S"])

In [32]:
JM_DS_GS_HJ_data = data[(data["PRDSPC_ID"] == JM_DS_GS_HJ[0])| (data["PRDSPC_ID"] == JM_DS_GS_HJ[1]) | (data["PRDSPC_ID"] == JM_DS_GS_HJ[2]) ]
JM_DS_GS_HJ_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
10,1173DK,22A13B70111,2022A13B70,22A13B70111,HBZ051210,NaN,NaN,1282N,1282N,NaN,...,1065A,0,2022-03-08 13:35:00,NaT,NaT,NaN,NaN,1055A,E,1510P
20,1173DK,22C13B65111,2022C13B65,22C13B65111,HBA055140A,22C13B65111,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-23 16:34:45,2022-09-15 01:20:32,NaT,NaN,NaN,1055A,E,1510P
21,1173DK,22C13B73112,2022C13B73,22C13B73112,HBB097230,22C13B73112,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-29 10:27:44,2022-09-14 22:23:11,NaT,NaN,NaN,1055A,E,1510P
22,1173DK,22C13C62111,2022C13C62,22C13C62111,HBY131730A,22C13C62111,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-07 09:12:23,2022-07-15 21:40:12,NaT,NaN,NaN,1055A,E,1510P
23,1173DK,22D12E321121A,2022D12E32,22D12E32112,HBC099530C,22D12E32112,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-14 21:51:42,2022-09-14 19:23:53,NaT,NaN,NaN,1055A,E,1510P

### ANN 0차

In [33]:
JM_DS_GS_HJ_data_ANN0 = JM_DS_GS_HJ_data[JM_DS_GS_HJ_data["PNSPRC_CD"] == "AN10"]
JM_DS_GS_HJ_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
23,1173DK,22D12E321121A,2022D12E32,22D12E32112,HBC099530C,22D12E32112,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-14 21:51:42,2022-09-14 19:23:53,NaT,NaN,NaN,1055A,E,1510P
362,1173DK,22H13026111,2022H13026,22H13026111,CPW58330,22H13026111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-16 15:51:50,2022-09-04 09:25:47,NaT,NaN,NaN,1055A,L,1510P
365,1173DK,22H13041111,2022H13041,22H13041111,CTW45530,22H13041111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 14:09:06,2022-09-03 10:19:40,NaT,NaN,NaN,1055A,E,1510P

In [34]:
JM_DS_GS_HJ_data_ANN0_size = len(JM_DS_GS_HJ_data_ANN0)
JM_DS_GS_HJ_data_ANN0_size

3

### ANN 1차 이상

In [35]:
JM_DS_GS_HJ_data_ANN1 = JM_DS_GS_HJ_data[JM_DS_GS_HJ_data["PNSPRC_CD"] != "AN10"]
JM_DS_GS_HJ_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
10,1173DK,22A13B70111,2022A13B70,22A13B70111,HBZ051210,NaN,NaN,1282N,1282N,NaN,...,1065A,0,2022-03-08 13:35:00,NaT,NaT,NaN,NaN,1055A,E,1510P
20,1173DK,22C13B65111,2022C13B65,22C13B65111,HBA055140A,22C13B65111,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-23 16:34:45,2022-09-15 01:20:32,NaT,NaN,NaN,1055A,E,1510P
21,1173DK,22C13B73112,2022C13B73,22C13B73112,HBB097230,22C13B73112,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-29 10:27:44,2022-09-14 22:23:11,NaT,NaN,NaN,1055A,E,1510P
22,1173DK,22C13C62111,2022C13C62,22C13C62111,HBY131730A,22C13C62111,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-07 09:12:23,2022-07-15 21:40:12,NaT,NaN,NaN,1055A,E,1510P
51,1173DK,22F130591111A,2022F13059,22F13059111,CRX30820,22F130591111A,101.0,1282N,1282N,NaN,...,1065A,0,2022-08-27 02:43:06,2022-09-07 20:03:08,NaT,NaN,NaN,1055A,L,1510P

In [36]:
JM_DS_GS_HJ_data_ANN1_size = len(JM_DS_GS_HJ_data_ANN1)
JM_DS_GS_HJ_data_ANN1_size

25

## NHK / NHK SPRING PREC / NHK SPRING(THA~)

In [37]:
NHK = np.array(["51CRV4M-S"])

In [38]:
NHK_data = data[data["PRDSPC_ID"] == NHK[0]]
NHK_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
233,1173DK,22H120342111A,2022H12034,22H12034211,HBF137390,22H120342111A,102.0,1282N,1282N,NaN,...,1065A,0,2022-08-26 04:31:45,2022-09-03 23:53:31,NaT,NaN,NaN,1055B,L,1510P
235,1173DK,22H120391111A,2022H12039,22H12039111,HBF137220,22H120391111A,101.0,1282N,1282N,NaN,...,1065A,0,2022-08-26 05:51:02,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P
236,1173DK,22H120392111A,2022H12039,22H12039211,HBF137220,22H120392111A,102.0,1282N,1282N,NaN,...,1065A,0,2022-08-26 05:51:21,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P
237,1173DK,22H120411111A,2022H12041,22H12041111,HBF137210,22H120411111A,101.0,1282N,1282N,NaN,...,1065A,0,2022-08-29 01:24:57,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P
238,1173DK,22H120412111A,2022H12041,22H12041211,HBF137210,22H120412111A,102.0,1282N,1282N,NaN,...,1065A,0,2022-08-29 01:25:14,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P

### ANN 0차

In [39]:
NHK_data_ANN0 = NHK_data[NHK_data["PNSPRC_CD"] == "AN10"]
NHK_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
312,1173DK,22H12187112,2022H12187,22H12187112,HBG167280,22H12187112,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 13:12:35,2022-09-04 09:25:47,NaT,NaN,NaN,1055A,L,1510P
327,1173DK,22H12214111,2022H12214,22H12214111,HBG167210,22H12214111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-25 09:50:57,2022-09-06 02:51:54,NaT,NaN,NaN,1055A,E,1510P
328,1173DK,22H12214112,2022H12214,22H12214112,HBG167200,22H12214112,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-25 09:50:57,2022-09-13 14:16:25,NaT,NaN,NaN,1055A,E,1510P
329,1173DK,22H12215111,2022H12215,22H12215111,HBG167070,22H12215111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-25 09:52:28,2022-09-13 13:50:03,NaT,NaN,NaN,1055A,E,1510P
330,1173DK,22H12216111,2022H12216,22H12216111,HBG167410,22H12216111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-25 09:53:38,2022-09-06 03:14:14,NaT,NaN,NaN,1055A,E,1510P

In [40]:
NHK_data_ANN0_size = len(NHK_data_ANN0)
NHK_data_ANN0_size

6

### ANN 1차 이상

In [41]:
NHK_data_ANN1 = NHK_data[NHK_data["PNSPRC_CD"] != "AN10"]
NHK_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
233,1173DK,22H120342111A,2022H12034,22H12034211,HBF137390,22H120342111A,102.0,1282N,1282N,NaN,...,1065A,0,2022-08-26 04:31:45,2022-09-03 23:53:31,NaT,NaN,NaN,1055B,L,1510P
235,1173DK,22H120391111A,2022H12039,22H12039111,HBF137220,22H120391111A,101.0,1282N,1282N,NaN,...,1065A,0,2022-08-26 05:51:02,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P
236,1173DK,22H120392111A,2022H12039,22H12039211,HBF137220,22H120392111A,102.0,1282N,1282N,NaN,...,1065A,0,2022-08-26 05:51:21,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P
237,1173DK,22H120411111A,2022H12041,22H12041111,HBF137210,22H120411111A,101.0,1282N,1282N,NaN,...,1065A,0,2022-08-29 01:24:57,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P
238,1173DK,22H120412111A,2022H12041,22H12041211,HBF137210,22H120412111A,102.0,1282N,1282N,NaN,...,1065A,0,2022-08-29 01:25:14,2022-09-03 23:53:31,NaT,NaN,NaN,1055A,L,1510P

In [42]:
NHK_data_ANN1_size = len(NHK_data_ANN1)
NHK_data_ANN1_size

12

## SCHAEFFLER GROUP

In [43]:
SCHAEFFLER = np.array(["CK75M2","CK75M3"])

In [44]:
SCHAEFFLER_data = data[(data["PRDSPC_ID"] == SCHAEFFLER[0]) | (data["PRDSPC_ID"] == SCHAEFFLER[1])]
SCHAEFFLER_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
45,1173DK,22F12H421111A,2022F12H42,22F12H42111,HBE112120B,22F12H421111A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-22 03:05:51,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
46,1173DK,22F12H421121A,2022F12H42,22F12H42112,HBE112120B,22F12H421121A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-22 03:07:39,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
47,1173DK,22F12T391111A,2022F12T39,22F12T39111,HBE112450B,22F12T391111A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-21 02:25:16,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
48,1173DK,22F12T391121A,2022F12T39,22F12T39112,HBE112450B,22F12T391121A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-21 04:17:06,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
84,1173DK,22G12224111,2022G12224,22G12224111,HBE071430,22G12224111,1.0,1282Y,1282Y,NaN,...,1065A,0,2022-08-16 15:02:33,2022-09-03 08:56:25,NaT,NaN,NaN,1055B,E,1510P

### ANN 0차

In [45]:
SCHAEFFLER_data_ANN0 = SCHAEFFLER_data[SCHAEFFLER_data["PNSPRC_CD"] == "AN10"]
SCHAEFFLER_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
313,1173DK,22H12194111,2022H12194,22H12194111,HBG136070A,22H12194111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 14:28:29,2022-09-04 09:57:31,NaT,NaN,NaN,1055B,L,1510P
314,1173DK,22H12194112,2022H12194,22H12194112,HBG135920,22H12194112,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 14:28:29,2022-09-05 14:38:40,NaT,NaN,NaN,1055B,L,1510P
315,1173DK,22H121951111A,2022H12195,22H12195111,HBG0882801,22H12195111,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-04 12:03:37,2022-09-04 05:05:14,NaT,NaN,NaN,1055B,E,1510P
316,1173DK,22H121952111A,2022H12195,22H12195211,HBG0882801,22H12195111,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-04 12:03:37,2022-09-04 05:05:14,NaT,NaN,NaN,1055B,E,1510P
317,1173DK,22H121953111A,2022H12195,22H12195311,HBG0882801,22H12195111,103.0,1282N,1282N,NaN,...,1065A,0,2022-09-04 12:03:37,2022-09-04 05:05:14,NaT,NaN,NaN,1055B,E,1510P

In [46]:
SCHAEFFLER_data_ANN0_size = len(SCHAEFFLER_data_ANN0)
SCHAEFFLER_data_ANN0_size

10

### ANN 1차,2차

In [47]:
SCHAEFFLER_data_ANN12 = SCHAEFFLER_data[(SCHAEFFLER_data["PNSPRC_CD"] == "AN11") | (SCHAEFFLER_data["PNSPRC_CD"] == "AN12")]
SCHAEFFLER_data_ANN12.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
45,1173DK,22F12H421111A,2022F12H42,22F12H42111,HBE112120B,22F12H421111A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-22 03:05:51,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
46,1173DK,22F12H421121A,2022F12H42,22F12H42112,HBE112120B,22F12H421121A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-22 03:07:39,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
47,1173DK,22F12T391111A,2022F12T39,22F12T39111,HBE112450B,22F12T391111A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-21 02:25:16,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
48,1173DK,22F12T391121A,2022F12T39,22F12T39112,HBE112450B,22F12T391121A,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-21 04:17:06,2022-09-02 16:10:51,NaT,NaN,NaN,1055B,E,1510P
84,1173DK,22G12224111,2022G12224,22G12224111,HBE071430,22G12224111,1.0,1282Y,1282Y,NaN,...,1065A,0,2022-08-16 15:02:33,2022-09-03 08:56:25,NaT,NaN,NaN,1055B,E,1510P

In [48]:
SCHAEFFLER_data_ANN12_size = len(SCHAEFFLER_data_ANN12)
SCHAEFFLER_data_ANN12_size

39

### ANN 3차

In [49]:
SCHAEFFLER_data_ANN3 = SCHAEFFLER_data[SCHAEFFLER_data["PNSPRC_CD"] == "AN13"]
SCHAEFFLER_data_ANN3.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

## SCHAEFFLER GROUP / HARSHA ENGINEE / LUK / 나라엠앤디 /(주)대유단조

In [50]:
SCHA_HAR_LUK_NARA_DAEU = np.array(["C80M"])

In [51]:
SCHA_HAR_LUK_NARA_DAEU_data = data[data["PRDSPC_ID"] == SCHA_HAR_LUK_NARA_DAEU[0]]
SCHA_HAR_LUK_NARA_DAEU_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
98,1173DK,22G12251111,2022G12251,22G12251111,HBV141770,22G12251111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-28 10:19:23,2022-08-31 06:32:49,NaT,NaN,NaN,1055A,E,1510P
114,1173DK,22G12C191111A,2022G12C19,22G12C19111,HBB085250,22G12C191111A,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-01 11:07:10,2022-09-05 08:30:45,NaT,NaN,NaN,1055A,E,1510P
115,1173DK,22G12C191121A,2022G12C19,22G12C19112,HBB085250,22G12C191121A,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-01 11:27:22,2022-09-05 08:31:32,NaT,NaN,NaN,1055A,E,1510P
116,1173DK,22G12C191131A,2022G12C19,22G12C19113,HBB085250,22G12C191131A,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-01 12:16:54,2022-09-05 09:45:06,NaT,NaN,NaN,1055A,E,1510P
117,1173DK,22G12C80111,2022G12C80,22G12C80111,HBF178160B,22G12C80111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 08:35:44,2022-09-02 13:44:06,NaT,NaN,NaN,1055A,E,1510P

### ANN 0차

In [52]:
SCHA_HAR_LUK_NARA_DAEU_data_ANN0 = SCHA_HAR_LUK_NARA_DAEU_data[SCHA_HAR_LUK_NARA_DAEU_data["PNSPRC_CD"] == "AN10"]
SCHA_HAR_LUK_NARA_DAEU_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
98,1173DK,22G12251111,2022G12251,22G12251111,HBV141770,22G12251111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-28 10:19:23,2022-08-31 06:32:49,NaT,NaN,NaN,1055A,E,1510P
263,1173DK,22H12093111,2022H12093,22H12093111,HBF178110,22H12093111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-11 10:18:49,2022-09-03 15:55:40,NaT,NaN,NaN,1055A,L,1510P
264,1173DK,22H12094111,2022H12094,22H12094111,HBB085340,22H12094111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-11 10:20:02,2022-09-03 15:55:40,NaT,NaN,NaN,1055A,L,1510P
265,1173DK,22H12095111,2022H12095,22H12095111,HBB085140A,22H12095111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-11 10:20:34,2022-09-03 15:55:40,NaT,NaN,NaN,1055A,L,1510P

In [53]:
SCHA_HAR_LUK_NARA_DAEU_data_ANN0_size = len(SCHA_HAR_LUK_NARA_DAEU_data_ANN0)
SCHA_HAR_LUK_NARA_DAEU_data_ANN0_size

4

### ANN 1차 이상

In [54]:
SCHA_HAR_LUK_NARA_DAEU_data_ANN1 = SCHA_HAR_LUK_NARA_DAEU_data[SCHA_HAR_LUK_NARA_DAEU_data["PNSPRC_CD"] != "AN10"]
SCHA_HAR_LUK_NARA_DAEU_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
114,1173DK,22G12C191111A,2022G12C19,22G12C19111,HBB085250,22G12C191111A,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-01 11:07:10,2022-09-05 08:30:45,NaT,NaN,NaN,1055A,E,1510P
115,1173DK,22G12C191121A,2022G12C19,22G12C19112,HBB085250,22G12C191121A,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-01 11:27:22,2022-09-05 08:31:32,NaT,NaN,NaN,1055A,E,1510P
116,1173DK,22G12C191131A,2022G12C19,22G12C19113,HBB085250,22G12C191131A,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-01 12:16:54,2022-09-05 09:45:06,NaT,NaN,NaN,1055A,E,1510P
117,1173DK,22G12C80111,2022G12C80,22G12C80111,HBF178160B,22G12C80111,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 08:35:44,2022-09-02 13:44:06,NaT,NaN,NaN,1055A,E,1510P
118,1173DK,22G12C80112,2022G12C80,22G12C80112,HBF178160B,22G12C80112,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-23 08:35:44,2022-09-02 14:17:26,NaT,NaN,NaN,1055A,E,1510P

In [55]:
SCHA_HAR_LUK_NARA_DAEU_data_ANN1_size = len(SCHA_HAR_LUK_NARA_DAEU_data_ANN1)
SCHA_HAR_LUK_NARA_DAEU_data_ANN1_size

5

## 시흥공장

In [56]:
Siheung = np.array(["SK강"])

In [57]:
Siheung_data = data[data["PRDSPC_ID"] == Siheung[0]]
Siheung_data.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

## HANWA CO / .LTD

In [58]:
HANWA_LTD = np.array(["SK85"])

In [59]:
HANWA_LTD_data = data[data["PRDSPC_ID"] == HANWA_LTD[0]]
HANWA_LTD_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
49,1173DK,22F13047111,2022F13047,22F13047111,HBB097210,22F13047111,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-23 14:45:18,2022-09-03 05:08:30,NaT,NaN,NaN,1055A,E,1510P
50,1173DK,22F13051112,2022F13051,22F13051112,HBZ101910,22F13051112,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-24 15:35:16,2022-09-03 05:08:30,NaT,NaN,NaN,1055A,E,1510P
121,1173DK,22G13015111,2022G13015,22G13015111,HBC144210,22G13015111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-05 17:14:05,2022-09-14 08:15:49,NaT,NaN,NaN,1055A,E,1510P
122,1173DK,22G13020111,2022G13020,22G13020111,HBD086240,22G13020111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-06 09:31:31,2022-09-14 09:08:17,NaT,NaN,NaN,1055A,E,1510P
356,1173DK,22H13007112,2022H13007,22H13007112,HBG136850A,22H13007112,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-08 09:18:27,2022-09-02 20:14:01,NaT,NaN,NaN,NaN,L,1510P

### ANN 0차

In [60]:
HANWA_LTD_data_data_ANN0 = HANWA_LTD_data[HANWA_LTD_data["PNSPRC_CD"] == "AN10"]
HANWA_LTD_data_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
356,1173DK,22H13007112,2022H13007,22H13007112,HBG136850A,22H13007112,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-08 09:18:27,2022-09-02 20:14:01,NaT,NaN,NaN,NaN,L,1510P
357,1173DK,22H13007113,2022H13007,22H13007113,HBG137430C,22H13007113,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-08 09:18:27,2022-09-02 20:14:00,NaT,NaN,NaN,NaN,L,1510P
358,1173DK,22H13007114,2022H13007,22H13007114,HBG136830A,22H13007114,1.0,1282N,1282N,NaN,...,1065A,0,2022-08-08 09:18:27,2022-09-02 20:14:01,NaT,NaN,NaN,NaN,L,1510P

In [61]:
HANWA_LTD_data_data_ANN0_size = len(HANWA_LTD_data_data_ANN0)
HANWA_LTD_data_data_ANN0_size

3

### ANN 1차 이상

In [62]:
HANWA_LTD_data_data_ANN1 = HANWA_LTD_data[HANWA_LTD_data["PNSPRC_CD"] != "AN10"]
HANWA_LTD_data_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
49,1173DK,22F13047111,2022F13047,22F13047111,HBB097210,22F13047111,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-23 14:45:18,2022-09-03 05:08:30,NaT,NaN,NaN,1055A,E,1510P
50,1173DK,22F13051112,2022F13051,22F13051112,HBZ101910,22F13051112,1.0,1282N,1282N,NaN,...,1065A,0,2022-06-24 15:35:16,2022-09-03 05:08:30,NaT,NaN,NaN,1055A,E,1510P
121,1173DK,22G13015111,2022G13015,22G13015111,HBC144210,22G13015111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-05 17:14:05,2022-09-14 08:15:49,NaT,NaN,NaN,1055A,E,1510P
122,1173DK,22G13020111,2022G13020,22G13020111,HBD086240,22G13020111,1.0,1282N,1282N,NaN,...,1065A,0,2022-07-06 09:31:31,2022-09-14 09:08:17,NaT,NaN,NaN,1055A,E,1510P

In [63]:
HANWA_LTD_data_data_ANN1_size = len(HANWA_LTD_data_data_ANN1)
HANWA_LTD_data_data_ANN1_size

4

## (주)지에스앤티 / 한국엔에스케이

In [64]:
GSNT_HKNSK = np.array(["100CR6","100CR6-PA","SUJ2","SAE52100"])

In [65]:
GSNT_HKNSK_data = data[(data["PRDSPC_ID"] == GSNT_HKNSK[0])| (data["PRDSPC_ID"] == GSNT_HKNSK[1]) | (data["PRDSPC_ID"] == GSNT_HKNSK[2]) | (data["PRDSPC_ID"] == GSNT_HKNSK[3])]
GSNT_HKNSK_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
393,1173DK,22J13014111,2022J13014,22J13014111,HBQ176480,NaN,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-13 11:23:05,NaT,NaT,NaN,NaN,1055E,E,1510P
394,1173DK,22J13014112,2022J13014,22J13014112,HBQ176460,NaN,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-13 11:23:05,NaT,NaT,NaN,NaN,1055E,E,1510P

### ANN 0차

In [66]:
GSNT_HKNSK_data_ANN0 = GSNT_HKNSK_data[GSNT_HKNSK_data["PNSPRC_CD"] == "AN10"]
GSNT_HKNSK_data_ANN0 .head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
393,1173DK,22J13014111,2022J13014,22J13014111,HBQ176480,NaN,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-13 11:23:05,NaT,NaT,NaN,NaN,1055E,E,1510P
394,1173DK,22J13014112,2022J13014,22J13014112,HBQ176460,NaN,1.0,1282N,1282N,NaN,...,1065A,0,2022-09-13 11:23:05,NaT,NaT,NaN,NaN,1055E,E,1510P

In [67]:
GSNT_HKNSK_data_ANN0_size = len(GSNT_HKNSK_data_ANN0)
GSNT_HKNSK_data_ANN0_size

2

### ANN 1차 이상

In [68]:
GSNT_HKNSK_data_ANN1 = GSNT_HKNSK_data[GSNT_HKNSK_data["PNSPRC_CD"] != "AN10"]
GSNT_HKNSK_data_ANN1 .head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

In [69]:
GSNT_HKNSK_data_ANN1_size = len(GSNT_HKNSK_data_ANN1)
GSNT_HKNSK_data_ANN1_size

0

## (주)아스픽 / (주)엠알인프라오토

In [70]:
ASPIC_MR = np.array(["AISI4140M-S"])

In [71]:
ASPIC_MR_data = data[data["PRDSPC_ID"] == ASPIC_MR[0]]
ASPIC_MR_data.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

## 유신정밀공업(주) / (주)화진금속

In [72]:
USIN_HJ = np.array(["50CRV4M-S"])

In [73]:
USIN_HJ_data = data[data["PRDSPC_ID"] == USIN_HJ[0]]
USIN_HJ_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
6,1173DK,21M12D061111A,2021M12D06,21M12D06111,HBY122970,21M12D06111,1.0,1282S,1282S,NaN,...,1065A,0,2022-09-01 16:47:55,2022-09-03 09:11:31,NaT,NaN,NaN,1055A,E,1510P
94,1173DK,22G12242111,2022G12242,22G12242111,HBF136990C,22G12242111,1.0,1282Y,1282Y,NaN,...,1065A,0,2022-07-27 13:19:17,2022-09-03 13:07:05,NaT,NaN,NaN,1055A,E,1510P

### ANN 0차

In [74]:
USIN_HJ_data_ANN0 = USIN_HJ_data[USIN_HJ_data["PNSPRC_CD"] == "AN10"]
USIN_HJ_data_ANN0.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
6,1173DK,21M12D061111A,2021M12D06,21M12D06111,HBY122970,21M12D06111,1.0,1282S,1282S,NaN,...,1065A,0,2022-09-01 16:47:55,2022-09-03 09:11:31,NaT,NaN,NaN,1055A,E,1510P

In [75]:
USIN_HJ_data_ANN0_size = len(USIN_HJ_data_ANN0)
USIN_HJ_data_ANN0_size

1

### ANN 1차 이상

In [76]:
USIN_HJ_data_ANN1 = USIN_HJ_data[USIN_HJ_data["PNSPRC_CD"] != "AN10"]
USIN_HJ_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
94,1173DK,22G12242111,2022G12242,22G12242111,HBF136990C,22G12242111,1.0,1282Y,1282Y,NaN,...,1065A,0,2022-07-27 13:19:17,2022-09-03 13:07:05,NaT,NaN,NaN,1055A,E,1510P

In [77]:
USIN_HJ_data_ANN1_size = len(USIN_HJ_data_ANN1)
USIN_HJ_data_ANN1_size

1

## 엔에스하이텍

In [78]:
NShitec = np.array(["S45CM-R"])

In [79]:
NShitec_data = data[data["PRDSPC_ID"] == NShitec[0]]
NShitec_data.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
77,1173DK,22G122021111A,2022G12202,22G12202111,CRW397701,22G12202111,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
78,1173DK,22G122021121A,2022G12202,22G12202112,CTX443601,22G12202112,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
79,1173DK,22G122022111A,2022G12202,22G12202211,CRW397701,22G12202111,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
80,1173DK,22G122022121A,2022G12202,22G12202212,CTX443601,22G12202112,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
81,1173DK,22G122023111A,2022G12202,22G12202311,CRW397701,22G12202111,103.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P

### ANN 0차

In [80]:
NShitec_data_ANN0 = NShitec_data[NShitec_data["PNSPRC_CD"] == "AN10"]
NShitec_data_ANN0.head()

Empty DataFrame
Columns: [BUS_CD, COIL_NO, LOT_NO, BASIC_COIL_NO, HOTCOI_NO, MOTCOI_NO, TRK_NO, EMG_CD, AFTEMG_CD, PKG_NO, MRGCOI_NO, PVSSTS_CD, PRVPRC_CD, PNSSTS_CD, PNSPRC_CD, AFTPRC_CD, BASPRC_CD, LASWRK_DT, LASPRC_CD, RSTPNT_ODN, RSTPRC_REM, AFTPRC_REM, PLNPRC_ID, CHGPRC_CD, DUM_YN, PRVLOT_NO, PRVCOI_NO, USGCHG_YN, USGCHG_CNT, USGCHG_DT, THK_LEN, WDT_LEN, LEN_LEN, WGT_WGT, IND_CD, OUD_LEN, GRD_CD, PURCOM_ID, RAWDIV_WGT, RAWSPC_ID, RAWSTL_CD, RAWTHK_LEN, RAWWDT_LEN, RAWLEN_LEN, RAW_WGT, SPC_NO, SALBRN_CD, CUS_ID, USR_ID, ORD_CD, PRDSPC_ID, PRD_CD, PRDKND_CD, STL_CD, STLDTL_CD, ORD_NO, ORD_SEQ, ORDTHK_LEN, ORDWDT_LEN, ORD_WGT, USG_CD, DLV_YMD, PKGMTH_CD, PKGMTH_YN, WGTDCS_CLS, NAXWGT_YN, PPL_TRK, FIRCRT_YMD, RSTHMAX_VAL, RSTHMIN_VAL, RSTCMAX_VAL, RSTCMIN_VAL, DIV_CD, SKP_QTY, MRG_CLS, PRCSPL_REM, CRMPLN_ODN, CRMRST_ODN, ANNPLN_ODN, ANNRST_ODN, WRKTRM_YMD, ENT_DT, ENTCHR_NO, OUT_DT, OUTCHR_ID, BRI_DT, BRICHR_ID, BRIRSN_CD, RET_DT, RETCHR_NO, RETRSN_CD, RET_WGT, SAMPCK_YN, PRDRESE_CD, PRDRESE_YMD, PRDRESE_NO, RESEND_YMD, RESENDCHR_NO, COIEND_CD, END_YN, ...]
Index: []

[0 rows x 113 columns]

In [81]:
NShitec_data_ANN0_size = len(NShitec_data_ANN0)
NShitec_data_ANN0_size

0

### ANN 1차 이상

In [82]:
NShitec_data_ANN1 = NShitec_data[NShitec_data["PNSPRC_CD"] != "AN10"]
NShitec_data_ANN1.head()

,BUS_CD,COIL_NO,LOT_NO,BASIC_COIL_NO,HOTCOI_NO,MOTCOI_NO,TRK_NO,EMG_CD,AFTEMG_CD,PKG_NO,...,WRK_CD,INP_WGT,CRT_DT,UPD_DT,COILEND_DT,SEMIPKG_YN,SEMIPKG_CD,PKG_CD,LEV2SE_YN,ZON_CD
77,1173DK,22G122021111A,2022G12202,22G12202111,CRW397701,22G12202111,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
78,1173DK,22G122021121A,2022G12202,22G12202112,CTX443601,22G12202112,101.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
79,1173DK,22G122022111A,2022G12202,22G12202211,CRW397701,22G12202111,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
80,1173DK,22G122022121A,2022G12202,22G12202212,CTX443601,22G12202112,102.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 03:47:26,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P
81,1173DK,22G122023111A,2022G12202,22G12202311,CRW397701,22G12202111,103.0,1282N,1282N,NaN,...,1065A,0,2022-09-03 04:18:31,2022-09-05 00:33:21,NaT,NaN,NaN,1055A,E,1510P

In [83]:
NShitec_data_ANN1_size = len(NShitec_data_ANN1)
NShitec_data_ANN1_size

6

In [84]:
ANN0_size = [HKBOG_data_ANN0_size,ILJINNTS_2_data_ANN0_size,JMI_data_ANN0_size,JM_DS_GS_HJ_data_ANN0_size,
            NHK_data_ANN0_size,SCHAEFFLER_data_ANN0_size,SCHA_HAR_LUK_NARA_DAEU_data_ANN0_size,
            HANWA_LTD_data_data_ANN0_size,GSNT_HKNSK_data_ANN0_size,
            USIN_HJ_data_ANN0_size,NShitec_data_ANN0_size,]

In [85]:
len(ANN0_size)

11

In [86]:
ANN1_size = [HKBOG_data_ANN1_size,ILJINNTS_2_data_ANN1_size,JMI_data_ANN1_size,JM_DS_GS_HJ_data_ANN1_size,
            NHK_data_ANN1_size,SCHAEFFLER_data_ANN12_size,SCHA_HAR_LUK_NARA_DAEU_data_ANN1_size,
            HANWA_LTD_data_data_ANN1_size,GSNT_HKNSK_data_ANN1_size,USIN_HJ_data_ANN1_size,NShitec_data_ANN1_size]

In [87]:
len(ANN1_size)

11

In [88]:
Company = ["HKBOG", "ILJINNTS_2", "JMI", "JM_DS_GS_HJ", "NHK", "SCHAEFFLER", "SCHA_HAR_LUK_NARA_DAEU", "HANWA_LTD", "GSNT_HKNSK", "USIN_HJ", "NShitec"]

In [89]:
Product_Code = ["S45CM-R", "SK4M-R, SK5M-R, SKS51M-R, SKS81M-R", "SAE1074M-R", "S55CM-S, SCM435M-S, SK5M-S", "51CRV4M-S", "CK75M2/M3", "C80M", "SK85", "100CR6, 100CR6-PA, SUJ2, SAE52100", "50CRV4M-S", "S45CM-R"]

In [90]:
ANN0_degree = ["-", "750","700","725(표준)", "725 x MAX", "735 x 25", "735", "750 x MAX", "750 x MAX", "750", "750"]

In [91]:
ANN1_degree = ["620", "700(표준)","-","725", "700 x MAX", "720 x 25", "720", "700(표준)", "750 x MAX", "750", "-"]

### ANN 재공 현황 DATA에 존재하는 Special Cycle 
ANN 0차와 ANN 1차 이상 둘 다 존재하지 않은 경우는 넣지 않았음  

SCHAEFFLER_GROUP은 ANN0/ ANN1~2/ ANN3차로 구분됨  
현재 데이터에서 3차는 존재하지 않았으므로 제외시켰음

In [92]:
Special_Cycle_df = pd.DataFrame({"Company" : Company, 
                                "제품규격코드" : Product_Code,
                                "ANN 0차" : ANN0_size,
                                "ANN 1차 이상" : ANN1_size,
                                "ANN0_degree" : ANN0_degree,
                                "ANN1_degree" : ANN1_degree
                                })

Special_Cycle_df

,Company,제품규격코드,ANN 0차,ANN 1차 이상,ANN0_degree,ANN1_degree
0,HKBOG,S45CM-R,0,6,-,620
1,ILJINNTS_2,"SK4M-R, SK5M-R, SKS51M-R, SKS81M-R",1,3,750,700(표준)
2,JMI,SAE1074M-R,1,0,700,-
3,JM_DS_GS_HJ,"S55CM-S, SCM435M-S, SK5M-S",3,25,725(표준),725
4,NHK,51CRV4M-S,6,12,725 x MAX,700 x MAX
5,SCHAEFFLER,CK75M2/M3,10,39,735 x 25,720 x 25
6,SCHA_HAR_LUK_NARA_DAEU,C80M,4,5,735,720
7,HANWA_LTD,SK85,3,4,750 x MAX,700(표준)
8,GSNT_HKNSK,"100CR6, 100CR6-PA, SUJ2, SAE52100",2,0,750 x MAX,750 x MAX
9,USIN_HJ,50CRV4M-S,1,1,750,750
10,NShitec,S45CM-R,0,6,750,-